name: pnpm
description: setup node.js environment

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '22'
  pnpm-version:
    description: pnpm version
    required: false
    default: '10'

outputs:
  pnpm_store_path:
    description: pnpm store path
    value: ${{ steps.pnpm-store.outputs.STORE_PATH }}

runs:
  using: composite
  steps:
    - id: setup-node
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: pnpm setup
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: pnpm store path
      id: pnpm-store
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

    - name: install
      shell: bash
      run: pnpm install --frozen-lockfile
