name: pnpm
description: setup node.js environment

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '22'
  pnpm-version:
    description: pnpm version
    required: false
    default: '10'

outputs:
  pnpm_store_path:
    description: pnpm store path
    value: ${{ steps.pnpm-store.outputs.STORE_PATH }}

runs:
  using: composite
  steps:
    - name: pnpm setup
      uses: pnpm/action-setup@v4
      with:
        run_install: false
      
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Activate pnpm ${{ inputs.pnpm-version }}
      shell: bash
      run: corepack prepare pnpm@${{ inputs.pnpm-version }} --activate

    - name: Check pnpm
      shell: bash
      run: |
        which pnpm || true
        pnpm -v
  
    - id: setup-node
      uses: actions/setup-node@v5
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: pnpm store path
      id: pnpm-store
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> "$GITHUB_OUTPUT"

    - name: install
      shell: bash
      run: pnpm install --frozen-lockfile
