name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/restore-turbo-cache
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: '24'
          pnpm-version: '10.15.1'

      - name: base sha
        id: base
        uses: ./.github/actions/base-sha

      - run: pnpm turbo run lint --cache-dir=.turbo --filter=...[${{ steps.base.outputs.sha }}]

  typecheck:
    name: typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/restore-turbo-cache
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: '24'
          pnpm-version: '10.15.1'

      - name: base sha
        id: base
        uses: ./.github/actions/base-sha

      - run: pnpm turbo run typecheck --cache-dir=.turbo --filter=...[${{ steps.base.outputs.sha }}]
  
  test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/restore-turbo-cache
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: '24'
          pnpm-version: '10.15.1'

      - name: base sha
        id: base
        uses: ./.github/actions/base-sha

      - run: pnpm turbo run test --cache-dir=.turbo --filter=...[${{ steps.base.outputs.sha }}]

  sonar:
    name: sonar
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [web, api]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/restore-turbo-cache
      - uses: ./.github/actions/setup-pnpm
        with:
          node-version: '24'
          pnpm-version: '10.15.1'
      - name: build & test - (${{ matrix.app }})
        run: |
          pnpm turbo run build --filter=./apps/${{ matrix.app }}
          pnpm turbo run test --filter=./apps/${{ matrix.app }} -- --coverage
      - name: Sonar scan (${{ matrix.app }})
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: apps/${{ matrix.app }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}